# Submitted by : Aryan Singh_RN12MAY2023
# Time Complexity : O(n)
# Space Complexity : O(n)
# Did this code successfully run on Leetcode : Yes
# Any problem you faced while coding this : No

class Solution:
    """
    Creating an array which will store the max value generated by all the numbers upto that point.
    Max is calculated either by including number at that point, or by rejecting it.
    """
    def rob(self, nums) -> int:
        result = [0 for i in range(len(nums) + 1)]
        # base case
        result[1] = nums[0]

        for i in range(2, len(nums) + 1):
            result[i] = max((result[i - 2] + nums[i -1]), result[i - 1])
        
        return result[len(nums)]


# testing method:  
def test_rob():
    s = Solution()
    nums = [2, 7, 9, 3, 1]
    expected_output = 12
    if s.rob(nums) == expected_output:
        print("Output is correct")
    else:
        print("Wrong output")


test_rob()